-- 自建 App 工厂字段（AppFactory::ensureSchema 也会自动补齐）
ALTER TABLE `pre_apps` ADD COLUMN `url` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `pre_apps` ADD COLUMN `theme` VARCHAR(32) DEFAULT NULL;
ALTER TABLE `pre_apps` ADD COLUMN `icon_path` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `pre_apps` ADD COLUMN `splash_path` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `pre_apps` ADD COLUMN `progress` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `pre_apps` ADD COLUMN `error` VARCHAR(500) DEFAULT NULL;
ALTER TABLE `pre_apps` ADD COLUMN `build_log` MEDIUMTEXT;
ALTER TABLE `pre_apps` ADD COLUMN `build_status` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `pre_apps` ADD COLUMN `nonav` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `pre_apps` ADD COLUMN `updatetime` DATETIME DEFAULT NULL;
